o erro não está por que,não existe user_products?  somente auth_users na coleção do banco de dados
FirebaseError: Failed to get document because the client is offline.